#!/bin/bash -login
 
#PBS -l walltime=4:00:00,nodes=1:ppn=1,mem=2gb
#PBS -j oe

### load necessary modules, e.g.
module load avida
 
### change to the working directory where your code is located
cd Documents/cse845f/chow_replication/replication_config_files
 
### call your executable
avida -a -set DATA_DIR ../data_100000 -set ENVIRONMENT_FILE environment_100000.cfg -set ANALYZE_FILE analyze_100000.cfg