#!/bin/bash -login
 
#PBS -l walltime=48:00:00,nodes=1:ppn=1,mem=2gb
#PBS -j oe
#PBS -t 1-30

### load necessary modules, e.g.
module load avida
 
### change to the working directory where your code is located
cd Documents/cse845f/chow_replication/replication_config_files
 
### call your executable
avida -set DATA_DIR ../data_100000/replicate_${PBS_ARRAYID} -set ENVIRONMENT_FILE environment_100000.cfg